name: Deploy to S3

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Node.js 버전

      # 의존성 설치
      - name: Install dependencies
        run: npm install

      # 프로젝트 빌드
      - name: Build project
        run: npm run build

      # 정적 파일 포함 준비
      - name: Copy static assets
        run: |
          mkdir -p ./out/fonts
          cp ./public/fonts/times-new-roman.otf ./out/fonts/times-new-roman.otf

      # S3로 배포
      - name: Deploy to S3
        run: |
          aws s3 sync ./out s3://irin-blog --delete --exclude "node_modules/*" --exclude ".git/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
